-- ===========================================================================
-- ChakulaFast — complete schema
--
-- GENERATED by `npm run db:bundle` from supabase/migrations/ on
-- 2026-08-27T10:31:45.473Z.
-- Do not edit: change the migrations and regenerate.
--
-- To apply: open your Supabase project > SQL Editor > New query, paste this
-- whole file, and Run. It is safe on a fresh project and expects to be run
-- exactly once.
--
-- 10 migrations, in order:
--   20260820090000_core_schema.sql
--   20260820090100_menu_and_orders.sql
--   20260820090200_registration_payments.sql
--   20260820090300_guard_triggers.sql
--   20260820090400_discovery_rpcs.sql
--   20260820090500_reviews.sql
--   20260820090600_storage_and_realtime.sql
--   20260820090700_order_line_integrity_and_admin.sql
--   20260825100000_fuzzy_dish_search.sql
--   20260825101000_vendor_analytics.sql
-- ===========================================================================


-- =========================================================================
-- 20260820090000_core_schema.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — core schema: roles, profiles, restaurants, opening hours.
--
-- Security model (same shape as the reference project):
--   * `user_roles` is the source of truth for authorisation. `profiles.role`
--     is a denormalised copy used only to render UI, and is kept in sync by
--     triggers. Nothing may grant itself a role — see handle_new_user().
--   * Every table has RLS on. Public/guest browsing is deliberate and narrow:
--     anon may read ACTIVE restaurants and their menus, nothing else.
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS extensions;

-- Trigram index backs the dish search ("ugali", "chip", …), which is a
-- leading-wildcard ILIKE and therefore unindexable any other way. Guarded so
-- the migration still applies on a Postgres where the extension isn't
-- available — search just falls back to a sequential scan.
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_trgm unavailable (%), dish search will not be index-backed', SQLERRM;
END $$;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
CREATE TYPE public.app_role AS ENUM ('customer', 'restaurant', 'admin');

-- A restaurant is invisible to customers until it has paid the one-time
-- registration fee and an admin (or the payment gateway) confirms it.
CREATE TYPE public.restaurant_status AS ENUM (
  'pending_payment',
  'active',
  'suspended',
  'rejected'
);

CREATE TYPE public.order_status AS ENUM (
  'pending',
  'accepted',
  'preparing',
  'ready',
  'completed',
  'cancelled'
);

CREATE TYPE public.payment_status AS ENUM ('pending', 'submitted', 'confirmed', 'failed');

CREATE TYPE public.payment_method AS ENUM (
  'mpesa',
  'tigopesa',
  'airtel',
  'halopesa',
  'bank',
  'cash',
  'manual'
);

CREATE TYPE public.menu_category AS ENUM (
  'local',
  'grills',
  'fast_food',
  'breakfast',
  'snacks',
  'drinks',
  'desserts'
);

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- Great-circle distance in km. IMMUTABLE so it can be used in indexes and
-- inlined into the search query's ORDER BY.
CREATE OR REPLACE FUNCTION public.haversine_km(
  lat1 double precision,
  lng1 double precision,
  lat2 double precision,
  lng2 double precision
)
RETURNS double precision
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT CASE
    WHEN lat1 IS NULL OR lng1 IS NULL OR lat2 IS NULL OR lng2 IS NULL THEN NULL
    ELSE 2 * 6371 * asin(sqrt(
      power(sin(radians(lat2 - lat1) / 2), 2)
      + cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lng2 - lng1) / 2), 2)
    ))
  END;
$$;

-- ---------------------------------------------------------------------------
-- Profiles + roles
-- ---------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT,
  avatar_url TEXT,
  town TEXT,
  role app_role NOT NULL DEFAULT 'customer',
  is_suspended BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  role app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role
  );
$$;

-- ---------------------------------------------------------------------------
-- Restaurants / hotels
-- ---------------------------------------------------------------------------
CREATE TABLE public.restaurants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL UNIQUE REFERENCES auth.users ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 2 AND 80),
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  description TEXT,
  phone TEXT,
  town TEXT NOT NULL,
  address TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
  logo_url TEXT,
  cover_url TEXT,
  status restaurant_status NOT NULL DEFAULT 'pending_payment',
  -- Fallback prep time used for restaurant-level ETA display; individual
  -- dishes carry their own prep_minutes and win when an order is placed.
  avg_prep_minutes INT NOT NULL DEFAULT 20 CHECK (avg_prep_minutes BETWEEN 1 AND 240),
  -- Vendor's own kill switch, independent of opening hours ("kitchen is
  -- swamped, stop taking pre-orders for now").
  is_accepting_orders BOOLEAN NOT NULL DEFAULT true,
  rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
  rating_count INT NOT NULL DEFAULT 0,
  suspended_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX restaurants_status_town_idx ON public.restaurants (status, town);
CREATE INDEX restaurants_slug_idx ON public.restaurants (slug);

CREATE TRIGGER trg_restaurants_touch
  BEFORE UPDATE ON public.restaurants
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- 0 = Sunday, matching JavaScript's Date#getDay() so the client never has to
-- remap. A missing row for a weekday means "closed that day".
CREATE TABLE public.restaurant_hours (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES public.restaurants ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  opens_at TIME NOT NULL DEFAULT '08:00',
  closes_at TIME NOT NULL DEFAULT '22:00',
  is_closed BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (restaurant_id, day_of_week)
);

CREATE INDEX restaurant_hours_restaurant_idx ON public.restaurant_hours (restaurant_id);

-- Everything user-facing is in Tanzanian local time regardless of where the
-- server or the browser thinks it is.
CREATE OR REPLACE FUNCTION public.is_restaurant_open(_restaurant_id UUID, _at TIMESTAMPTZ DEFAULT now())
RETURNS BOOLEAN
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  local_ts TIMESTAMP;
  h RECORD;
BEGIN
  local_ts := _at AT TIME ZONE 'Africa/Dar_es_Salaam';

  SELECT * INTO h
  FROM public.restaurant_hours
  WHERE restaurant_id = _restaurant_id
    AND day_of_week = EXTRACT(DOW FROM local_ts)::smallint;

  IF NOT FOUND OR h.is_closed THEN
    RETURN false;
  END IF;

  -- A closing time earlier than the opening time means the kitchen runs past
  -- midnight (e.g. 18:00 → 02:00), so the window wraps around the day.
  IF h.closes_at <= h.opens_at THEN
    RETURN local_ts::time >= h.opens_at OR local_ts::time < h.closes_at;
  END IF;

  RETURN local_ts::time BETWEEN h.opens_at AND h.closes_at;
END;
$$;

-- ---------------------------------------------------------------------------
-- Signup trigger: create the profile and the role row together.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _role app_role;
BEGIN
  _role := COALESCE(
    NULLIF(NEW.raw_user_meta_data ->> 'role', '')::app_role,
    'customer'
  );

  -- Signup metadata is attacker-controlled: anyone can put role=admin in the
  -- signUp() options. Only 'customer' and 'restaurant' are self-selectable;
  -- admins are made with the service role (scripts/seed-admin.mjs).
  IF _role NOT IN ('customer', 'restaurant') THEN
    _role := 'customer';
  END IF;

  INSERT INTO public.profiles (id, full_name, phone, town, role)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'full_name', ''), NEW.email, 'Guest'),
    NEW.raw_user_meta_data ->> 'phone',
    NEW.raw_user_meta_data ->> 'town',
    _role
  );

  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, _role);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_hours ENABLE ROW LEVEL SECURITY;

-- profiles ------------------------------------------------------------------
CREATE POLICY "Users read own profile" ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id OR public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Users update own profile" ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- No INSERT policy: handle_new_user() (SECURITY DEFINER) is the only writer.

-- user_roles ----------------------------------------------------------------
CREATE POLICY "Users read own roles" ON public.user_roles
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));

-- Deliberately no INSERT/UPDATE/DELETE policies. Roles are assigned by the
-- signup trigger or by an admin through a server function using the service
-- role key, never by the user themselves.

-- restaurants ---------------------------------------------------------------
-- Guests must be able to browse, so this one policy covers anon too. Only
-- ACTIVE restaurants are exposed; a pending/suspended one is invisible to
-- everyone except its owner and admins.
CREATE POLICY "Anyone can view active restaurants" ON public.restaurants
  FOR SELECT TO anon, authenticated
  USING (status = 'active');

CREATE POLICY "Owner views own restaurant" ON public.restaurants
  FOR SELECT TO authenticated
  USING (auth.uid() = owner_id);

CREATE POLICY "Admins view all restaurants" ON public.restaurants
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Restaurant users create own listing" ON public.restaurants
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = owner_id
    AND public.has_role(auth.uid(), 'restaurant')
    -- A brand new listing always starts unpaid; only the payment flow or an
    -- admin can move it on (see the guard trigger in the guards migration).
    AND status = 'pending_payment'
  );

CREATE POLICY "Owner updates own restaurant" ON public.restaurants
  FOR UPDATE TO authenticated
  USING (auth.uid() = owner_id)
  WITH CHECK (auth.uid() = owner_id);

-- restaurant_hours ----------------------------------------------------------
CREATE POLICY "Anyone can view hours of active restaurants" ON public.restaurant_hours
  FOR SELECT TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = restaurant_hours.restaurant_id AND r.status = 'active'
    )
  );

CREATE POLICY "Owner manages own hours" ON public.restaurant_hours
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = restaurant_hours.restaurant_id AND r.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = restaurant_hours.restaurant_id AND r.owner_id = auth.uid()
    )
  );

CREATE POLICY "Admins manage hours" ON public.restaurant_hours
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));


-- =========================================================================
-- 20260820090100_menu_and_orders.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — menus, pre-orders, order history and live arrival pings.
--
-- The pre-order ("ready on arrival") flow lives here:
--   orders.expected_arrival_at  — when the customer says they'll walk in
--   orders.prep_minutes         — longest prep time in the basket, snapshotted
--   → the vendor board renders "start cooking at" = arrival − prep, so the
--     food lands on the counter as the customer does.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Menu items
-- ---------------------------------------------------------------------------
CREATE TABLE public.menu_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES public.restaurants ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 2 AND 80),
  description TEXT,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  category menu_category NOT NULL DEFAULT 'local',
  photo_url TEXT,
  prep_minutes INT NOT NULL DEFAULT 15 CHECK (prep_minutes BETWEEN 1 AND 240),
  is_available BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  -- Denormalised so the search only ever touches one indexed column.
  search_text TEXT GENERATED ALWAYS AS (
    lower(name || ' ' || coalesce(description, ''))
  ) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX menu_items_restaurant_idx ON public.menu_items (restaurant_id, sort_order);
CREATE INDEX menu_items_category_idx ON public.menu_items (category) WHERE is_available;

DO $$
BEGIN
  CREATE INDEX menu_items_search_trgm_idx
    ON public.menu_items USING gin (search_text extensions.gin_trgm_ops);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping trigram index on menu_items (%)', SQLERRM;
END $$;

CREATE TRIGGER trg_menu_items_touch
  BEFORE UPDATE ON public.menu_items
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------
CREATE TABLE public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Short, sayable code — what the customer reads out at the counter.
  code TEXT NOT NULL UNIQUE,
  customer_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  -- RESTRICT, not CASCADE: a restaurant with order history can be suspended
  -- but must never take its financial record with it when deleted.
  restaurant_id UUID NOT NULL REFERENCES public.restaurants ON DELETE RESTRICT,
  status order_status NOT NULL DEFAULT 'pending',
  subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  note TEXT,
  customer_phone TEXT,
  customer_lat DOUBLE PRECISION,
  customer_lng DOUBLE PRECISION,
  -- 'manual' = the customer picked "I'll be there in N minutes".
  -- 'gps'    = estimated from their live position and refreshed by pings.
  arrival_mode TEXT NOT NULL DEFAULT 'manual' CHECK (arrival_mode IN ('manual', 'gps')),
  arrival_minutes INT NOT NULL DEFAULT 15 CHECK (arrival_minutes BETWEEN 0 AND 240),
  expected_arrival_at TIMESTAMPTZ NOT NULL,
  -- Snapshot of the slowest dish in the basket, so the "start cooking at"
  -- countdown stays correct even if the vendor later edits the menu.
  prep_minutes INT NOT NULL DEFAULT 0,
  accepted_at TIMESTAMPTZ,
  preparing_at TIMESTAMPTZ,
  ready_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancel_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX orders_restaurant_idx ON public.orders (restaurant_id, status, created_at DESC);
CREATE INDEX orders_customer_idx ON public.orders (customer_id, created_at DESC);
CREATE INDEX orders_live_idx ON public.orders (expected_arrival_at)
  WHERE status IN ('pending', 'accepted', 'preparing', 'ready');

CREATE TRIGGER trg_orders_touch
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TABLE public.order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES public.orders ON DELETE CASCADE,
  -- SET NULL rather than cascade: deleting a dish from the menu must not
  -- erase what somebody actually bought. The name/price snapshots below are
  -- what the receipt renders from.
  menu_item_id UUID REFERENCES public.menu_items ON DELETE SET NULL,
  name TEXT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
  prep_minutes INT NOT NULL DEFAULT 15,
  qty INT NOT NULL CHECK (qty BETWEEN 1 AND 50),
  line_total NUMERIC(10, 2) GENERATED ALWAYS AS (unit_price * qty) STORED
);

CREATE INDEX order_items_order_idx ON public.order_items (order_id);

-- Append-only status history. Powers the customer's tracker and gives admins
-- something to read when a vendor and a customer disagree about what happened.
CREATE TABLE public.order_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES public.orders ON DELETE CASCADE,
  status order_status NOT NULL,
  actor_id UUID REFERENCES auth.users ON DELETE SET NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX order_events_order_idx ON public.order_events (order_id, created_at);

-- Live "I'm on my way" pings. Each one can move the arrival estimate, which
-- is what lets the kitchen re-time a dish when the customer hits traffic.
CREATE TABLE public.order_pings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES public.orders ON DELETE CASCADE,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  distance_km DOUBLE PRECISION,
  eta_minutes INT CHECK (eta_minutes BETWEEN 0 AND 240),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX order_pings_order_idx ON public.order_pings (order_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Order code + derived fields
-- ---------------------------------------------------------------------------
-- Alphabet excludes 0/O/1/I so a code read aloud over a noisy counter can't
-- be mistranscribed.
CREATE OR REPLACE FUNCTION public.gen_order_code()
RETURNS TEXT
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
  alphabet CONSTANT TEXT := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  candidate TEXT;
  i INT;
BEGIN
  LOOP
    candidate := 'CF-';
    FOR i IN 1..5 LOOP
      candidate := candidate || substr(alphabet, floor(random() * length(alphabet))::int + 1, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.orders WHERE code = candidate);
  END LOOP;
  RETURN candidate;
END;
$$;

CREATE OR REPLACE FUNCTION public.prepare_order()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.code IS NULL OR NEW.code = '' THEN
    NEW.code := public.gen_order_code();
  END IF;

  -- The client sends "in N minutes"; the absolute instant is derived here so
  -- a wrong clock in the browser can't shift the kitchen's countdown.
  NEW.expected_arrival_at := now() + make_interval(mins => NEW.arrival_minutes);

  -- Every derived field starts empty no matter what the client posted.
  -- Totals and prep time are filled in by recalc_order_totals() once the
  -- line items land; the pipeline timestamps are stamped by the guard
  -- trigger as the order actually moves through the kitchen.
  NEW.subtotal := 0;
  NEW.total := 0;
  NEW.prep_minutes := 0;
  NEW.accepted_at := NULL;
  NEW.preparing_at := NULL;
  NEW.ready_at := NULL;
  NEW.completed_at := NULL;
  NEW.cancelled_at := NULL;
  NEW.cancel_reason := NULL;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prepare_order
  BEFORE INSERT ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.prepare_order();

-- Totals and prep time are derived from the line items, never trusted from
-- the client. Runs on every basket mutation while the order is still open.
CREATE OR REPLACE FUNCTION public.recalc_order_totals()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target UUID := COALESCE(NEW.order_id, OLD.order_id);
  sum_total NUMERIC(10, 2);
  max_prep INT;
BEGIN
  SELECT COALESCE(sum(line_total), 0), COALESCE(max(prep_minutes), 0)
    INTO sum_total, max_prep
  FROM public.order_items
  WHERE order_id = target;

  UPDATE public.orders
     SET subtotal = sum_total,
         -- No platform commission on orders: ChakulaFast monetises through
         -- the one-time restaurant registration fee, so total = subtotal.
         -- Keeping both columns leaves room for fees/discounts later.
         total = sum_total,
         prep_minutes = max_prep
   WHERE id = target;

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_recalc_order_totals
  AFTER INSERT OR UPDATE OR DELETE ON public.order_items
  FOR EACH ROW EXECUTE FUNCTION public.recalc_order_totals();

-- A ping refreshes the arrival estimate, but only for GPS-tracked orders —
-- if the customer explicitly said "15 minutes", that's their commitment and
-- a stray location reading shouldn't override it.
CREATE OR REPLACE FUNCTION public.apply_order_ping()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.eta_minutes IS NULL THEN
    RETURN NULL;
  END IF;

  UPDATE public.orders
     SET expected_arrival_at = now() + make_interval(mins => NEW.eta_minutes),
         customer_lat = NEW.lat,
         customer_lng = NEW.lng
   WHERE id = NEW.order_id
     AND arrival_mode = 'gps'
     AND status IN ('pending', 'accepted', 'preparing', 'ready');

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_apply_order_ping
  AFTER INSERT ON public.order_pings
  FOR EACH ROW EXECUTE FUNCTION public.apply_order_ping();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_pings ENABLE ROW LEVEL SECURITY;

-- menu_items ----------------------------------------------------------------
CREATE POLICY "Anyone can view menus of active restaurants" ON public.menu_items
  FOR SELECT TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = menu_items.restaurant_id AND r.status = 'active'
    )
  );

CREATE POLICY "Owner manages own menu" ON public.menu_items
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = menu_items.restaurant_id AND r.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = menu_items.restaurant_id AND r.owner_id = auth.uid()
    )
  );

CREATE POLICY "Admins view all menus" ON public.menu_items
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- orders --------------------------------------------------------------------
CREATE POLICY "Customer views own orders" ON public.orders
  FOR SELECT TO authenticated
  USING (auth.uid() = customer_id);

CREATE POLICY "Restaurant views its orders" ON public.orders
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = orders.restaurant_id AND r.owner_id = auth.uid()
    )
  );

CREATE POLICY "Admins view all orders" ON public.orders
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Only a signed-in customer can create an order, only for themselves, only
-- at an active restaurant that is currently accepting them.
CREATE POLICY "Customer places own order" ON public.orders
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = customer_id
    AND status = 'pending'
    AND EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = orders.restaurant_id
        AND r.status = 'active'
        AND r.is_accepting_orders
    )
  );

-- The row-level rule is "a participant may update"; *what* they may change is
-- narrowed further by guard_order_update() in the guards migration.
CREATE POLICY "Participants update order" ON public.orders
  FOR UPDATE TO authenticated
  USING (
    auth.uid() = customer_id
    OR EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = orders.restaurant_id AND r.owner_id = auth.uid()
    )
  );

-- order_items ---------------------------------------------------------------
CREATE POLICY "Participants view order items" ON public.order_items
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      LEFT JOIN public.restaurants r ON r.id = o.restaurant_id
      WHERE o.id = order_items.order_id
        AND (o.customer_id = auth.uid() OR r.owner_id = auth.uid())
    )
    OR public.has_role(auth.uid(), 'admin')
  );

-- Lines can only be added while the order is still untouched by the kitchen.
CREATE POLICY "Customer fills own basket" ON public.order_items
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_items.order_id
        AND o.customer_id = auth.uid()
        AND o.status = 'pending'
    )
  );

CREATE POLICY "Customer removes own basket lines" ON public.order_items
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_items.order_id
        AND o.customer_id = auth.uid()
        AND o.status = 'pending'
    )
  );

-- order_events --------------------------------------------------------------
CREATE POLICY "Participants view order events" ON public.order_events
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      LEFT JOIN public.restaurants r ON r.id = o.restaurant_id
      WHERE o.id = order_events.order_id
        AND (o.customer_id = auth.uid() OR r.owner_id = auth.uid())
    )
    OR public.has_role(auth.uid(), 'admin')
  );

-- Deliberately no INSERT policy — the log is written only by the
-- SECURITY DEFINER trigger, so it can't be forged.

-- order_pings ---------------------------------------------------------------
CREATE POLICY "Participants view pings" ON public.order_pings
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      LEFT JOIN public.restaurants r ON r.id = o.restaurant_id
      WHERE o.id = order_pings.order_id
        AND (o.customer_id = auth.uid() OR r.owner_id = auth.uid())
    )
  );

CREATE POLICY "Customer pings own live order" ON public.order_pings
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_pings.order_id
        AND o.customer_id = auth.uid()
        AND o.status IN ('pending', 'accepted', 'preparing', 'ready')
    )
  );


-- =========================================================================
-- 20260820090200_registration_payments.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — the one-time restaurant registration fee (5,000 TZS).
--
-- Flow while PAYMENT_PROVIDER=manual:
--   1. Restaurant signs up and creates its listing  → status 'pending_payment'
--   2. Restaurant pays by mobile money and records the transaction reference
--      → registration_payments row, status 'submitted'
--   3. Admin verifies the reference and marks it received
--      → status 'confirmed' → activate_restaurant_on_payment() flips the
--        restaurant to 'active' and its menu becomes visible to customers
--
-- When a real gateway is wired up, step 3 is driven by the provider's webhook
-- instead of a human; nothing else in the flow changes.
-- ===========================================================================

-- Single-row settings table so the platform owner can change the fee or the
-- payment instructions from the admin console instead of shipping a migration.
CREATE TABLE public.platform_settings (
  id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),
  registration_fee_tzs NUMERIC(10, 2) NOT NULL DEFAULT 5000 CHECK (registration_fee_tzs >= 0),
  currency TEXT NOT NULL DEFAULT 'TZS',
  till_number TEXT,
  payment_instructions TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.platform_settings (id, payment_instructions)
VALUES (
  true,
  'Pay the registration fee to the platform till number, then enter the transaction reference from the confirmation SMS below. An administrator will verify it and activate your listing.'
);

CREATE TRIGGER trg_platform_settings_touch
  BEFORE UPDATE ON public.platform_settings
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE OR REPLACE FUNCTION public.registration_fee_tzs()
RETURNS NUMERIC
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT registration_fee_tzs FROM public.platform_settings WHERE id), 5000);
$$;

CREATE TABLE public.registration_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES public.restaurants ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'TZS',
  method payment_method NOT NULL DEFAULT 'manual',
  -- Transaction ID from the mobile money confirmation SMS.
  reference TEXT,
  -- Phone number the payment came from, for reconciliation.
  msisdn TEXT,
  status payment_status NOT NULL DEFAULT 'pending',
  -- Raw gateway response, once there is a gateway. Never rendered to a user.
  provider_payload JSONB,
  note TEXT,
  submitted_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  confirmed_by UUID REFERENCES auth.users ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX registration_payments_restaurant_idx
  ON public.registration_payments (restaurant_id, created_at DESC);
CREATE INDEX registration_payments_status_idx
  ON public.registration_payments (status, created_at DESC);

-- A restaurant pays once. Failed and pending attempts may pile up; exactly one
-- of them is ever allowed to reach 'confirmed'.
CREATE UNIQUE INDEX registration_payments_one_confirmed_idx
  ON public.registration_payments (restaurant_id)
  WHERE status = 'confirmed';

CREATE TRIGGER trg_registration_payments_touch
  BEFORE UPDATE ON public.registration_payments
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- The amount is set from platform_settings, never from the request body —
-- otherwise a restaurant could submit a 1 TZS payment and get activated.
CREATE OR REPLACE FUNCTION public.prepare_registration_payment()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.amount := public.registration_fee_tzs();
  NEW.currency := COALESCE(
    (SELECT currency FROM public.platform_settings WHERE id),
    'TZS'
  );

  -- Only an admin (or a gateway webhook running as the service role) may
  -- create an already-confirmed payment.
  IF NEW.status = 'confirmed' AND auth.uid() IS NOT NULL
     AND NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'A payment cannot be created as already confirmed';
  END IF;

  IF NEW.status = 'submitted' AND NEW.submitted_at IS NULL THEN
    NEW.submitted_at := now();
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prepare_registration_payment
  BEFORE INSERT ON public.registration_payments
  FOR EACH ROW EXECUTE FUNCTION public.prepare_registration_payment();

-- Confirming a payment is the single event that puts a restaurant live.
CREATE OR REPLACE FUNCTION public.activate_restaurant_on_payment()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.status = 'confirmed' AND OLD.status IS DISTINCT FROM 'confirmed' THEN
    -- confirmed_at / confirmed_by are stamped by stamp_payment_confirmation()
    -- (a BEFORE UPDATE trigger added in a later migration), so this only has
    -- the listing to deal with.
    --
    -- Only lifts a listing that is waiting on payment. A suspended or
    -- rejected restaurant stays where the admin put it — money alone
    -- shouldn't undo a moderation decision.
    UPDATE public.restaurants
       SET status = 'active'
     WHERE id = NEW.restaurant_id
       AND status = 'pending_payment';
  END IF;

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_activate_restaurant_on_payment
  AFTER UPDATE ON public.registration_payments
  FOR EACH ROW EXECUTE FUNCTION public.activate_restaurant_on_payment();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registration_payments ENABLE ROW LEVEL SECURITY;

-- Vendors need to read the fee and the payment instructions.
CREATE POLICY "Signed-in users read platform settings" ON public.platform_settings
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Admins update platform settings" ON public.platform_settings
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Owner views own payments" ON public.registration_payments
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = registration_payments.restaurant_id AND r.owner_id = auth.uid()
    )
  );

CREATE POLICY "Admins view all payments" ON public.registration_payments
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Owner submits own payment" ON public.registration_payments
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = registration_payments.restaurant_id AND r.owner_id = auth.uid()
    )
    AND status IN ('pending', 'submitted')
  );

-- Confirming is an admin action only. Vendors cannot mark their own payment
-- received, and cannot edit a reference after submitting it.
CREATE POLICY "Admins update payments" ON public.registration_payments
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));


-- =========================================================================
-- 20260820090300_guard_triggers.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — integrity guards.
--
-- RLS answers "may this user touch this row at all?". These triggers answer
-- the narrower question "may they change *this column*, to *this value*,
-- right now?" — which is what actually keeps a customer from zeroing their
-- bill or a vendor from marking their own listing active without paying.
--
-- Two escape hatches, used consistently below:
--   pg_trigger_depth() > 1 → the write came from another trigger of ours
--                            (totals recalc, rating rollup, activation),
--                            which has already been vetted.
--   auth.uid() IS NULL     → no JWT, i.e. the service role: server functions,
--                            seed scripts and gateway webhooks.
--
-- Every RAISE EXCEPTION message here is written to be shown to a user
-- verbatim; src/lib/errorMessages.ts allow-lists them by prefix.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- profiles: nobody promotes themselves
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.guard_profile_update()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF pg_trigger_depth() > 1 OR auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF public.has_role(auth.uid(), 'admin') THEN
    RETURN NEW;
  END IF;

  IF NEW.role IS DISTINCT FROM OLD.role THEN
    RAISE EXCEPTION 'Cannot change role directly';
  END IF;

  IF NEW.is_suspended IS DISTINCT FROM OLD.is_suspended THEN
    RAISE EXCEPTION 'Cannot change account status directly';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_profile_update
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.guard_profile_update();

CREATE TRIGGER trg_profiles_touch
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- user_roles is the source of truth; profiles.role is the copy the UI reads.
-- Keeping them in sync here means an admin action only has to write one table
-- and the two can never drift.
CREATE OR REPLACE FUNCTION public.sync_profile_role()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target UUID := COALESCE(NEW.user_id, OLD.user_id);
  effective app_role;
BEGIN
  -- Highest privilege wins if a user somehow holds more than one role.
  SELECT role INTO effective
  FROM public.user_roles
  WHERE user_id = target
  ORDER BY CASE role WHEN 'admin' THEN 0 WHEN 'restaurant' THEN 1 ELSE 2 END
  LIMIT 1;

  UPDATE public.profiles
     SET role = COALESCE(effective, 'customer')
   WHERE id = target;

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_sync_profile_role
  AFTER INSERT OR UPDATE OR DELETE ON public.user_roles
  FOR EACH ROW EXECUTE FUNCTION public.sync_profile_role();

-- ---------------------------------------------------------------------------
-- restaurants: a vendor cannot publish or re-rate itself
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.guard_restaurant_update()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF pg_trigger_depth() > 1 OR auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF public.has_role(auth.uid(), 'admin') THEN
    RETURN NEW;
  END IF;

  IF NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN
    RAISE EXCEPTION 'Cannot transfer a restaurant to another owner';
  END IF;

  -- This is the load-bearing check for the whole business model: the only
  -- path from 'pending_payment' to 'active' is a confirmed payment.
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    RAISE EXCEPTION 'Listing status is set by the platform, not by the restaurant';
  END IF;

  IF NEW.rating IS DISTINCT FROM OLD.rating
     OR NEW.rating_count IS DISTINCT FROM OLD.rating_count THEN
    RAISE EXCEPTION 'Ratings are calculated from customer reviews';
  END IF;

  -- The slug is a public URL that customers may have bookmarked or shared.
  IF NEW.slug IS DISTINCT FROM OLD.slug THEN
    RAISE EXCEPTION 'Cannot change the restaurant web address once it is set';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_restaurant_update
  BEFORE UPDATE ON public.restaurants
  FOR EACH ROW EXECUTE FUNCTION public.guard_restaurant_update();

-- ---------------------------------------------------------------------------
-- orders: the status pipeline
--
--   pending ──▶ accepted ──▶ preparing ──▶ ready ──▶ completed
--      │            │            │           │
--      └────────────┴────────────┴───────────┴──▶ cancelled
--
-- The customer may cancel only before cooking starts. The kitchen drives
-- every other transition, one step at a time.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.guard_order_update()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  uid UUID := auth.uid();
  is_customer BOOLEAN;
  is_vendor BOOLEAN;
BEGIN
  -- Stamped first, for EVERY writer including admins, server functions and
  -- the service role. These are derived values that must never come from the
  -- client, and putting them after the authorisation short-circuits below
  -- meant an admin nudging a stuck order left ready_at/completed_at null —
  -- which silently zeroed the vendor's ready-on-time metric.
  NEW.accepted_at  := COALESCE(OLD.accepted_at,  CASE WHEN NEW.status = 'accepted'  THEN now() END);
  NEW.preparing_at := COALESCE(OLD.preparing_at, CASE WHEN NEW.status = 'preparing' THEN now() END);
  NEW.ready_at     := COALESCE(OLD.ready_at,     CASE WHEN NEW.status = 'ready'     THEN now() END);
  NEW.completed_at := COALESCE(OLD.completed_at, CASE WHEN NEW.status = 'completed' THEN now() END);
  NEW.cancelled_at := COALESCE(OLD.cancelled_at, CASE WHEN NEW.status = 'cancelled' THEN now() END);

  IF pg_trigger_depth() > 1 OR uid IS NULL THEN
    RETURN NEW;
  END IF;

  IF public.has_role(uid, 'admin') THEN
    RETURN NEW;
  END IF;

  is_customer := uid = OLD.customer_id;
  is_vendor := EXISTS (
    SELECT 1 FROM public.restaurants r
    WHERE r.id = OLD.restaurant_id AND r.owner_id = uid
  );

  IF NOT (is_customer OR is_vendor) THEN
    RAISE EXCEPTION 'Not authorized to update this order';
  END IF;

  -- Identity and money are fixed once the order exists.
  IF NEW.code IS DISTINCT FROM OLD.code
     OR NEW.customer_id IS DISTINCT FROM OLD.customer_id
     OR NEW.restaurant_id IS DISTINCT FROM OLD.restaurant_id
     OR NEW.subtotal IS DISTINCT FROM OLD.subtotal
     OR NEW.total IS DISTINCT FROM OLD.total
     OR NEW.prep_minutes IS DISTINCT FROM OLD.prep_minutes
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Order details cannot be changed after it is placed';
  END IF;

  IF is_customer THEN
    IF NEW.status IS DISTINCT FROM OLD.status
       AND NOT (NEW.status = 'cancelled' AND OLD.status IN ('pending', 'accepted')) THEN
      RAISE EXCEPTION 'Order can only be cancelled before the kitchen starts cooking';
    END IF;
  ELSE
    -- Vendor: one step at a time, forwards, or cancel with a reason.
    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
         (OLD.status = 'pending'   AND NEW.status IN ('accepted', 'cancelled'))
      OR (OLD.status = 'accepted'  AND NEW.status IN ('preparing', 'cancelled'))
      OR (OLD.status = 'preparing' AND NEW.status IN ('ready', 'cancelled'))
      OR (OLD.status = 'ready'     AND NEW.status IN ('completed', 'cancelled'))
    ) THEN
      RAISE EXCEPTION 'Order status cannot move from % to %', OLD.status, NEW.status;
    END IF;

    -- When the customer will arrive is the customer's call, not the kitchen's.
    IF NEW.arrival_mode IS DISTINCT FROM OLD.arrival_mode
       OR NEW.arrival_minutes IS DISTINCT FROM OLD.arrival_minutes
       OR NEW.expected_arrival_at IS DISTINCT FROM OLD.expected_arrival_at
       OR NEW.note IS DISTINCT FROM OLD.note
       OR NEW.customer_phone IS DISTINCT FROM OLD.customer_phone THEN
      RAISE EXCEPTION 'The kitchen cannot change the customer arrival details';
    END IF;
  END IF;

  -- (Pipeline timestamps are stamped at the top of this function, before the
  -- authorisation short-circuits, so every writer gets them.)
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_order_update
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.guard_order_update();

-- ---------------------------------------------------------------------------
-- order_events: written only from here, so the history cannot be forged
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_order_event()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.status IS NOT DISTINCT FROM OLD.status THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.order_events (order_id, status, actor_id, note)
  VALUES (
    NEW.id,
    NEW.status,
    auth.uid(),
    CASE WHEN NEW.status = 'cancelled' THEN NEW.cancel_reason END
  );

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_log_order_event
  AFTER INSERT OR UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.log_order_event();


-- =========================================================================
-- 20260820090400_discovery_rpcs.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — discovery.
--
-- The headline query: "I'm in Moshi and I want ugali — who has it, how much,
-- how far, and how long will it take?". One round trip returns the dish, the
-- restaurant, the distance and whether the kitchen is open right now.
--
-- Both functions are SECURITY INVOKER on purpose: RLS already restricts
-- restaurants/menu_items to status = 'active' for anon and authenticated
-- alike, so guests get exactly the same public view without any extra
-- surface area. The redundant `r.status = 'active'` predicates below let the
-- planner use restaurants_status_town_idx instead of relying on the policy.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.search_dishes(
  _q TEXT DEFAULT NULL,
  _lat DOUBLE PRECISION DEFAULT NULL,
  _lng DOUBLE PRECISION DEFAULT NULL,
  _town TEXT DEFAULT NULL,
  _category menu_category DEFAULT NULL,
  _max_km DOUBLE PRECISION DEFAULT NULL,
  _max_price NUMERIC DEFAULT NULL,
  _open_only BOOLEAN DEFAULT false,
  _available_only BOOLEAN DEFAULT true,
  _sort TEXT DEFAULT 'distance',
  _limit INT DEFAULT 60
)
RETURNS TABLE (
  item_id UUID,
  item_name TEXT,
  description TEXT,
  price NUMERIC,
  category menu_category,
  photo_url TEXT,
  prep_minutes INT,
  is_available BOOLEAN,
  restaurant_id UUID,
  restaurant_name TEXT,
  slug TEXT,
  town TEXT,
  address TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  logo_url TEXT,
  rating NUMERIC,
  rating_count INT,
  is_accepting_orders BOOLEAN,
  is_open BOOLEAN,
  distance_km DOUBLE PRECISION
)
LANGUAGE plpgsql STABLE SET search_path = public AS $$
#variable_conflict use_column
BEGIN
  RETURN QUERY
  WITH base AS (
    SELECT
      mi.id            AS item_id,
      mi.name          AS item_name,
      mi.description   AS description,
      mi.price         AS price,
      mi.category      AS category,
      mi.photo_url     AS photo_url,
      mi.prep_minutes  AS prep_minutes,
      mi.is_available  AS is_available,
      r.id             AS restaurant_id,
      r.name           AS restaurant_name,
      r.slug           AS slug,
      r.town           AS town,
      r.address        AS address,
      r.lat            AS lat,
      r.lng            AS lng,
      r.logo_url       AS logo_url,
      r.rating         AS rating,
      r.rating_count   AS rating_count,
      r.is_accepting_orders AS is_accepting_orders,
      public.is_restaurant_open(r.id) AS is_open,
      public.haversine_km(_lat, _lng, r.lat, r.lng) AS distance_km
    FROM public.menu_items mi
    JOIN public.restaurants r ON r.id = mi.restaurant_id
    WHERE r.status = 'active'
      -- Substring match, not prefix: "ugali" has to find "Ugali na maharage"
      -- and "Nyama choma na ugali" alike. Backed by the trigram index.
      AND (_q IS NULL OR btrim(_q) = '' OR mi.search_text LIKE '%' || lower(btrim(_q)) || '%')
      AND (_town IS NULL OR btrim(_town) = '' OR lower(r.town) = lower(btrim(_town)))
      AND (_category IS NULL OR mi.category = _category)
      AND (_max_price IS NULL OR mi.price <= _max_price)
      AND (NOT _available_only OR mi.is_available)
  )
  SELECT
    b.item_id, b.item_name, b.description, b.price, b.category, b.photo_url,
    b.prep_minutes, b.is_available, b.restaurant_id, b.restaurant_name, b.slug,
    b.town, b.address, b.lat, b.lng, b.logo_url, b.rating, b.rating_count,
    b.is_accepting_orders, b.is_open, b.distance_km
  FROM base b
  -- A NULL distance means the customer shared no location; filtering those
  -- out would leave a location-less visitor with an empty page.
  WHERE (_max_km IS NULL OR b.distance_km IS NULL OR b.distance_km <= _max_km)
    AND (NOT _open_only OR b.is_open)
  ORDER BY
    CASE WHEN _sort = 'price_asc'  THEN b.price END ASC NULLS LAST,
    CASE WHEN _sort = 'price_desc' THEN b.price END DESC NULLS LAST,
    CASE WHEN _sort = 'distance'   THEN b.distance_km END ASC NULLS LAST,
    CASE WHEN _sort = 'rating'     THEN b.rating END DESC NULLS LAST,
    CASE WHEN _sort = 'prep'       THEN b.prep_minutes END ASC NULLS LAST,
    -- Deterministic tie-break, and the fallback when _sort is unrecognised.
    b.distance_km ASC NULLS LAST,
    b.price ASC,
    b.item_id ASC
  LIMIT LEAST(GREATEST(COALESCE(_limit, 60), 1), 200);
END;
$$;

GRANT EXECUTE ON FUNCTION public.search_dishes(
  TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, menu_category,
  DOUBLE PRECISION, NUMERIC, BOOLEAN, BOOLEAN, TEXT, INT
) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- Restaurants near a point — powers the map view and the "around you" list.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.restaurants_nearby(
  _lat DOUBLE PRECISION DEFAULT NULL,
  _lng DOUBLE PRECISION DEFAULT NULL,
  _town TEXT DEFAULT NULL,
  _max_km DOUBLE PRECISION DEFAULT NULL,
  _open_only BOOLEAN DEFAULT false,
  _limit INT DEFAULT 60
)
RETURNS TABLE (
  id UUID,
  name TEXT,
  slug TEXT,
  description TEXT,
  town TEXT,
  address TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  logo_url TEXT,
  cover_url TEXT,
  rating NUMERIC,
  rating_count INT,
  avg_prep_minutes INT,
  is_accepting_orders BOOLEAN,
  is_open BOOLEAN,
  distance_km DOUBLE PRECISION,
  dish_count BIGINT,
  min_price NUMERIC
)
LANGUAGE plpgsql STABLE SET search_path = public AS $$
#variable_conflict use_column
BEGIN
  RETURN QUERY
  WITH base AS (
    SELECT
      r.id, r.name, r.slug, r.description, r.town, r.address, r.lat, r.lng,
      r.logo_url, r.cover_url, r.rating, r.rating_count, r.avg_prep_minutes,
      r.is_accepting_orders,
      public.is_restaurant_open(r.id) AS is_open,
      public.haversine_km(_lat, _lng, r.lat, r.lng) AS distance_km,
      (SELECT count(*) FROM public.menu_items mi
        WHERE mi.restaurant_id = r.id AND mi.is_available) AS dish_count,
      (SELECT min(mi.price) FROM public.menu_items mi
        WHERE mi.restaurant_id = r.id AND mi.is_available) AS min_price
    FROM public.restaurants r
    WHERE r.status = 'active'
      AND (_town IS NULL OR btrim(_town) = '' OR lower(r.town) = lower(btrim(_town)))
  )
  SELECT
    b.id, b.name, b.slug, b.description, b.town, b.address, b.lat, b.lng,
    b.logo_url, b.cover_url, b.rating, b.rating_count, b.avg_prep_minutes,
    b.is_accepting_orders, b.is_open, b.distance_km, b.dish_count, b.min_price
  FROM base b
  WHERE (_max_km IS NULL OR b.distance_km IS NULL OR b.distance_km <= _max_km)
    AND (NOT _open_only OR b.is_open)
  ORDER BY b.distance_km ASC NULLS LAST, b.rating DESC, b.name ASC
  LIMIT LEAST(GREATEST(COALESCE(_limit, 60), 1), 200);
END;
$$;

GRANT EXECUTE ON FUNCTION public.restaurants_nearby(
  DOUBLE PRECISION, DOUBLE PRECISION, TEXT, DOUBLE PRECISION, BOOLEAN, INT
) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- Towns that actually have something to order, for the manual area picker.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.active_towns()
RETURNS TABLE (town TEXT, restaurant_count BIGINT)
LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT r.town, count(*) AS restaurant_count
  FROM public.restaurants r
  WHERE r.status = 'active'
  GROUP BY r.town
  ORDER BY count(*) DESC, r.town ASC;
$$;

GRANT EXECUTE ON FUNCTION public.active_towns() TO anon, authenticated;


-- =========================================================================
-- 20260820090500_reviews.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — reviews.
--
-- Only a customer who actually collected an order can review, once, and only
-- the restaurant that cooked it. That constraint is what makes "sort by
-- rating" mean anything.
-- ===========================================================================

CREATE TABLE public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL UNIQUE REFERENCES public.orders ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  restaurant_id UUID NOT NULL REFERENCES public.restaurants ON DELETE CASCADE,
  stars INT NOT NULL CHECK (stars BETWEEN 1 AND 5),
  comment TEXT CHECK (comment IS NULL OR length(comment) <= 1000),
  -- Recorded because it is the promise the app makes: was the food actually
  -- ready when they walked in? Surfaced on the restaurant page.
  was_ready_on_time BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX reviews_restaurant_idx ON public.reviews (restaurant_id, created_at DESC);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read reviews of active restaurants" ON public.reviews
  FOR SELECT TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = reviews.restaurant_id AND r.status = 'active'
    )
  );

CREATE POLICY "Owner and admin read own reviews" ON public.reviews
  FOR SELECT TO authenticated
  USING (
    auth.uid() = customer_id
    OR public.has_role(auth.uid(), 'admin')
    OR EXISTS (
      SELECT 1 FROM public.restaurants r
      WHERE r.id = reviews.restaurant_id AND r.owner_id = auth.uid()
    )
  );

-- The order must be theirs, completed, and at the restaurant being reviewed.
CREATE POLICY "Customer reviews own completed order" ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = customer_id
    AND EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = reviews.order_id
        AND o.customer_id = auth.uid()
        AND o.restaurant_id = reviews.restaurant_id
        AND o.status = 'completed'
    )
  );

CREATE POLICY "Customer edits own review" ON public.reviews
  FOR UPDATE TO authenticated
  USING (auth.uid() = customer_id)
  WITH CHECK (auth.uid() = customer_id);

-- Rollup rather than an aggregate on read: the rating is displayed on every
-- search result row, so it needs to be a column, not a subquery.
CREATE OR REPLACE FUNCTION public.recalc_restaurant_rating()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target UUID := COALESCE(NEW.restaurant_id, OLD.restaurant_id);
BEGIN
  UPDATE public.restaurants r
     SET rating = COALESCE((
           SELECT round(avg(rv.stars)::numeric, 2)
           FROM public.reviews rv WHERE rv.restaurant_id = target
         ), 0),
         rating_count = (
           SELECT count(*) FROM public.reviews rv WHERE rv.restaurant_id = target
         )
   WHERE r.id = target;

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_recalc_restaurant_rating
  AFTER INSERT OR UPDATE OR DELETE ON public.reviews
  FOR EACH ROW EXECUTE FUNCTION public.recalc_restaurant_rating();

-- ---------------------------------------------------------------------------
-- Public review feed for a restaurant page.
--
-- `profiles` is deliberately readable only by its owner and admins, so a
-- plain join can't get the reviewer's name. This function exposes exactly one
-- extra field — the first name — and nothing else from the profile, which is
-- the smallest disclosure that still makes a review look like it came from a
-- person rather than from nobody.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.restaurant_reviews(_restaurant_id UUID, _limit INT DEFAULT 20)
RETURNS TABLE (
  id UUID,
  stars INT,
  comment TEXT,
  was_ready_on_time BOOLEAN,
  created_at TIMESTAMPTZ,
  reviewer_first_name TEXT
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT
    rv.id,
    rv.stars,
    rv.comment,
    rv.was_ready_on_time,
    rv.created_at,
    split_part(btrim(p.full_name), ' ', 1) AS reviewer_first_name
  FROM public.reviews rv
  JOIN public.restaurants r ON r.id = rv.restaurant_id
  LEFT JOIN public.profiles p ON p.id = rv.customer_id
  WHERE rv.restaurant_id = _restaurant_id
    -- SECURITY DEFINER bypasses RLS, so the "only active restaurants are
    -- public" rule has to be restated here explicitly.
    AND r.status = 'active'
  ORDER BY rv.created_at DESC
  LIMIT LEAST(GREATEST(COALESCE(_limit, 20), 1), 100);
$$;

GRANT EXECUTE ON FUNCTION public.restaurant_reviews(UUID, INT) TO anon, authenticated;

-- Called directly by the restaurant page to render its open/closed badge from
-- the same logic the search results use.
GRANT EXECUTE ON FUNCTION public.is_restaurant_open(UUID, TIMESTAMPTZ) TO anon, authenticated;


-- =========================================================================
-- 20260820090600_storage_and_realtime.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — image storage and realtime publication.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Storage: dish photos, restaurant logos/covers, customer avatars.
--
-- One public bucket, partitioned by uploader: every object must live under
-- `{auth.uid()}/…`, which is what the folder check below enforces. Public
-- read is intentional — menu photos are shown to guests who have no session.
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('menu-photos', 'menu-photos', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Menu photos are publicly readable" ON storage.objects;
CREATE POLICY "Menu photos are publicly readable" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'menu-photos');

DROP POLICY IF EXISTS "Users upload into own folder" ON storage.objects;
CREATE POLICY "Users upload into own folder" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'menu-photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

DROP POLICY IF EXISTS "Users replace own uploads" ON storage.objects;
CREATE POLICY "Users replace own uploads" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'menu-photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

DROP POLICY IF EXISTS "Users delete own uploads" ON storage.objects;
CREATE POLICY "Users delete own uploads" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'menu-photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- ---------------------------------------------------------------------------
-- Realtime
--
-- REPLICA IDENTITY FULL so subscribers receive the previous row on UPDATE —
-- without it the vendor board can't tell an accepted order from a re-ping,
-- and the customer's status tracker misses transitions.
--
-- Realtime respects RLS, so a vendor subscribed to `orders` still only
-- receives rows for their own restaurant.
-- ---------------------------------------------------------------------------
ALTER TABLE public.orders REPLICA IDENTITY FULL;
ALTER TABLE public.order_events REPLICA IDENTITY FULL;
ALTER TABLE public.order_pings REPLICA IDENTITY FULL;
ALTER TABLE public.restaurants REPLICA IDENTITY FULL;
ALTER TABLE public.registration_payments REPLICA IDENTITY FULL;

-- menu_items is deliberately NOT set to REPLICA IDENTITY FULL.
--
-- It carries a STORED GENERATED column (search_text), and from PostgreSQL 18
-- a published table whose replica identity includes an unpublished generated
-- column rejects every UPDATE:
--
--   ERROR 42P10: cannot update table "menu_items"
--   DETAIL: Replica identity must not contain unpublished generated columns.
--
-- That would break every menu edit — including the out-of-stock toggle the
-- vendor screen leans on during service. The default replica identity (the
-- primary key) is all this table needs anyway: subscribers here only use the
-- event to refetch, and INSERT/UPDATE payloads carry the full new row
-- regardless of replica identity. Only the *old* row is trimmed, and nothing
-- subscribes to menu_items deletions.

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'orders', 'order_events', 'order_pings',
    'menu_items', 'restaurants', 'registration_payments'
  ] LOOP
    BEGIN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    EXCEPTION
      WHEN duplicate_object THEN NULL;
      WHEN undefined_object THEN
        RAISE NOTICE 'supabase_realtime publication missing; skipping %', t;
    END;
  END LOOP;
END $$;


-- =========================================================================
-- 20260820090700_order_line_integrity_and_admin.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — order line integrity + the admin console's write access.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Prices come from the menu, never from the request body.
--
-- Without this, a customer could POST an order line with unit_price = 1 and
-- the totals trigger would faithfully compute a 1 TSh bill. Overwriting the
-- snapshot columns from the live menu row closes that off at the database,
-- so it holds no matter which client is talking to it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.prepare_order_item()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  mi RECORD;
  ord RECORD;
BEGIN
  SELECT restaurant_id, status INTO ord FROM public.orders WHERE id = NEW.order_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That order no longer exists';
  END IF;

  IF NEW.menu_item_id IS NULL THEN
    RAISE EXCEPTION 'Every order line must reference a dish on the menu';
  END IF;

  SELECT id, restaurant_id, name, price, prep_minutes, is_available
    INTO mi
  FROM public.menu_items
  WHERE id = NEW.menu_item_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'That dish is no longer on the menu';
  END IF;

  IF mi.restaurant_id <> ord.restaurant_id THEN
    RAISE EXCEPTION 'An order cannot mix dishes from different restaurants';
  END IF;

  IF NOT mi.is_available THEN
    RAISE EXCEPTION 'That dish is out of stock right now';
  END IF;

  NEW.name := mi.name;
  NEW.unit_price := mi.price;
  NEW.prep_minutes := mi.prep_minutes;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prepare_order_item
  BEFORE INSERT ON public.order_items
  FOR EACH ROW EXECUTE FUNCTION public.prepare_order_item();

-- ---------------------------------------------------------------------------
-- Whoever confirms a payment is recorded automatically, so the audit trail
-- can't be attributed to somebody else.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.stamp_payment_confirmation()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.status = 'confirmed' AND OLD.status IS DISTINCT FROM 'confirmed' THEN
    NEW.confirmed_at := COALESCE(NEW.confirmed_at, now());
    NEW.confirmed_by := COALESCE(auth.uid(), NEW.confirmed_by);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_stamp_payment_confirmation
  BEFORE UPDATE ON public.registration_payments
  FOR EACH ROW EXECUTE FUNCTION public.stamp_payment_confirmation();

-- ---------------------------------------------------------------------------
-- Admin write access.
--
-- Reads were granted in the earlier migrations; these are the writes the
-- admin console needs: approve/suspend a listing, correct a profile, and
-- step into a stuck order. Every one is gated on has_role(admin), and the
-- guard triggers already let admins through.
-- ---------------------------------------------------------------------------
CREATE POLICY "Admins update restaurants" ON public.restaurants
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins update profiles" ON public.profiles
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins update orders" ON public.orders
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins manage menus" ON public.menu_items
  FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Deliberately no DELETE policy on restaurants for anyone, including admins:
-- orders reference them ON DELETE RESTRICT, so a listing with history can
-- only be suspended. The one case where deletion is safe (a listing that
-- never took an order) is handled by adminDeleteRestaurant in
-- src/lib/adminRestaurants.functions.ts, which checks first and explains
-- itself if it can't.


-- =========================================================================
-- 20260825100000_fuzzy_dish_search.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — typo-tolerant dish search.
--
-- Someone hunting for lunch types "ugaly", "chipsi mayai" or "piliau" and the
-- substring match returns nothing, which reads as "no kitchen near you sells
-- this" rather than "you misspelled it". That is the worst possible failure
-- for the app's single most important query.
--
-- Fixed with pg_trgm's word-similarity operator (`<%`), which compares the
-- query against the closest word-boundary run inside search_text:
--
--   word_similarity('ugaly', 'ugali na maharage') = 0.67   -> matches
--   similarity     ('ugaly', 'ugali na maharage') = 0.20   -> would not
--
-- word_similarity is the right one precisely because a dish name is a few
-- words and the query is usually one of them. Plain similarity() dilutes the
-- score across the whole string and misses.
--
-- `<%` is index-backed by the existing GIN trigram index on search_text, so
-- this stays a cheap query rather than a sequential scan with a function call
-- per row.
-- ===========================================================================

-- The index and operator are load-bearing now rather than a nice-to-have, so
-- this is no longer wrapped in an exception handler: if pg_trgm genuinely
-- cannot be installed we want the migration to say so, not to silently ship
-- a search that can't spell.
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

DO $$
BEGIN
  CREATE INDEX menu_items_search_trgm_idx
    ON public.menu_items USING gin (search_text extensions.gin_trgm_ops);
EXCEPTION WHEN duplicate_table THEN
  NULL; -- already created by the core schema migration
END $$;

-- CREATE OR REPLACE cannot change a function's return type, and this adds
-- is_fuzzy_match to the returned row — so the old signature has to go first.
DROP FUNCTION IF EXISTS public.search_dishes(
  TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, menu_category,
  DOUBLE PRECISION, NUMERIC, BOOLEAN, BOOLEAN, TEXT, INT
);

CREATE FUNCTION public.search_dishes(
  _q TEXT DEFAULT NULL,
  _lat DOUBLE PRECISION DEFAULT NULL,
  _lng DOUBLE PRECISION DEFAULT NULL,
  _town TEXT DEFAULT NULL,
  _category menu_category DEFAULT NULL,
  _max_km DOUBLE PRECISION DEFAULT NULL,
  _max_price NUMERIC DEFAULT NULL,
  _open_only BOOLEAN DEFAULT false,
  _available_only BOOLEAN DEFAULT true,
  _sort TEXT DEFAULT 'distance',
  _limit INT DEFAULT 60
)
RETURNS TABLE (
  item_id UUID,
  item_name TEXT,
  description TEXT,
  price NUMERIC,
  category menu_category,
  photo_url TEXT,
  prep_minutes INT,
  is_available BOOLEAN,
  restaurant_id UUID,
  restaurant_name TEXT,
  slug TEXT,
  town TEXT,
  address TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  logo_url TEXT,
  rating NUMERIC,
  rating_count INT,
  is_accepting_orders BOOLEAN,
  is_open BOOLEAN,
  distance_km DOUBLE PRECISION,
  -- true when the dish only matched approximately, so the UI can say
  -- "showing results for ugali" instead of pretending it was exact.
  is_fuzzy_match BOOLEAN
)
LANGUAGE plpgsql STABLE SET search_path = public, extensions AS $$
#variable_conflict use_column
DECLARE
  needle TEXT := lower(btrim(COALESCE(_q, '')));
  -- Below three characters a trigram query matches almost everything, so
  -- fuzzy matching is only enabled once there is enough to go on.
  fuzzy_ok BOOLEAN := length(needle) >= 3;
BEGIN
  RETURN QUERY
  WITH base AS (
    SELECT
      mi.id            AS item_id,
      mi.name          AS item_name,
      mi.description   AS description,
      mi.price         AS price,
      mi.category      AS category,
      mi.photo_url     AS photo_url,
      mi.prep_minutes  AS prep_minutes,
      mi.is_available  AS is_available,
      r.id             AS restaurant_id,
      r.name           AS restaurant_name,
      r.slug           AS slug,
      r.town           AS town,
      r.address        AS address,
      r.lat            AS lat,
      r.lng            AS lng,
      r.logo_url       AS logo_url,
      r.rating         AS rating,
      r.rating_count   AS rating_count,
      r.is_accepting_orders AS is_accepting_orders,
      public.is_restaurant_open(r.id) AS is_open,
      public.haversine_km(_lat, _lng, r.lat, r.lng) AS distance_km,
      (needle <> '' AND mi.search_text NOT LIKE '%' || needle || '%') AS is_fuzzy_match
    FROM public.menu_items mi
    JOIN public.restaurants r ON r.id = mi.restaurant_id
    WHERE r.status = 'active'
      AND (
        needle = ''
        -- Exact substring first: "ugali" has to find both "Ugali na
        -- maharage" and "Nyama choma na ugali".
        OR mi.search_text LIKE '%' || needle || '%'
        -- Then the near-miss: index-backed word similarity.
        OR (fuzzy_ok AND needle <% mi.search_text)
      )
      AND (_town IS NULL OR btrim(_town) = '' OR lower(r.town) = lower(btrim(_town)))
      AND (_category IS NULL OR mi.category = _category)
      AND (_max_price IS NULL OR mi.price <= _max_price)
      AND (NOT _available_only OR mi.is_available)
  )
  SELECT
    b.item_id, b.item_name, b.description, b.price, b.category, b.photo_url,
    b.prep_minutes, b.is_available, b.restaurant_id, b.restaurant_name, b.slug,
    b.town, b.address, b.lat, b.lng, b.logo_url, b.rating, b.rating_count,
    b.is_accepting_orders, b.is_open, b.distance_km, b.is_fuzzy_match
  FROM base b
  WHERE (_max_km IS NULL OR b.distance_km IS NULL OR b.distance_km <= _max_km)
    AND (NOT _open_only OR b.is_open)
  ORDER BY
    -- Anything that matched exactly outranks a near-miss, whatever the
    -- chosen sort. Sorting a typo's approximate hits above a real match
    -- would make the feature feel broken even when it worked.
    b.is_fuzzy_match ASC,
    CASE WHEN _sort = 'price_asc'  THEN b.price END ASC NULLS LAST,
    CASE WHEN _sort = 'price_desc' THEN b.price END DESC NULLS LAST,
    CASE WHEN _sort = 'distance'   THEN b.distance_km END ASC NULLS LAST,
    CASE WHEN _sort = 'rating'     THEN b.rating END DESC NULLS LAST,
    CASE WHEN _sort = 'prep'       THEN b.prep_minutes END ASC NULLS LAST,
    b.distance_km ASC NULLS LAST,
    b.price ASC,
    b.item_id ASC
  LIMIT LEAST(GREATEST(COALESCE(_limit, 60), 1), 200);
END;
$$;

GRANT EXECUTE ON FUNCTION public.search_dishes(
  TEXT, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, menu_category,
  DOUBLE PRECISION, NUMERIC, BOOLEAN, BOOLEAN, TEXT, INT
) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- "Did you mean…" — the closest real dish name to what was typed.
--
-- Powers the correction line above the results. Deliberately a separate,
-- cheap call rather than another column on every result row.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.suggest_dish(_q TEXT)
RETURNS TEXT
LANGUAGE sql STABLE SET search_path = public, extensions AS $$
  SELECT mi.name
  FROM public.menu_items mi
  JOIN public.restaurants r ON r.id = mi.restaurant_id
  WHERE r.status = 'active'
    AND mi.is_available
    AND length(btrim(COALESCE(_q, ''))) >= 3
    AND lower(btrim(_q)) <% mi.search_text
  ORDER BY extensions.word_similarity(lower(btrim(_q)), mi.search_text) DESC, mi.name ASC
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.suggest_dish(TEXT) TO anon, authenticated;


-- =========================================================================
-- 20260825101000_vendor_analytics.sql
-- =========================================================================

-- ===========================================================================
-- ChakulaFast — vendor analytics.
--
-- A restaurant owner's two real questions are "what am I taking?" and "what
-- should I prep for?". Both are aggregations over their own orders, which is
-- work Postgres should do rather than shipping every order to the browser to
-- be summed there.
--
-- All three functions are SECURITY DEFINER and therefore bypass RLS, so each
-- one re-checks ownership explicitly against auth.uid() before returning a
-- single row. An admin is allowed through as well, for support.
-- ===========================================================================

-- Shared gate. Raises rather than returning empty so a mistake is loud.
CREATE OR REPLACE FUNCTION public.assert_owns_restaurant(_restaurant_id UUID)
RETURNS VOID
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN; -- service role: trusted server-side caller
  END IF;

  IF public.has_role(auth.uid(), 'admin') THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.restaurants r
    WHERE r.id = _restaurant_id AND r.owner_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Not authorized to view this restaurant';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.assert_owns_restaurant(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.assert_owns_restaurant(UUID) TO authenticated;

-- ---------------------------------------------------------------------------
-- Headline numbers over a rolling window.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.vendor_summary(_restaurant_id UUID, _days INT DEFAULT 30)
RETURNS TABLE (
  orders_total BIGINT,
  orders_completed BIGINT,
  orders_cancelled BIGINT,
  takings NUMERIC,
  average_order NUMERIC,
  -- The promise the platform makes, measured: of the orders that were marked
  -- ready, how many were ready before the customer said they'd arrive.
  ready_on_time_pct NUMERIC,
  -- Median minutes from 'accepted' to 'ready'. Median, not mean, because one
  -- forgotten ticket left open overnight would wreck an average.
  median_prep_minutes NUMERIC,
  rating NUMERIC,
  rating_count INT
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
#variable_conflict use_column
DECLARE
  since TIMESTAMPTZ := now() - make_interval(days => GREATEST(COALESCE(_days, 30), 1));
BEGIN
  PERFORM public.assert_owns_restaurant(_restaurant_id);

  RETURN QUERY
  WITH o AS (
    SELECT * FROM public.orders
    WHERE restaurant_id = _restaurant_id AND created_at >= since
  )
  SELECT
    count(*)::bigint,
    count(*) FILTER (WHERE o.status = 'completed')::bigint,
    count(*) FILTER (WHERE o.status = 'cancelled')::bigint,
    COALESCE(sum(o.total) FILTER (WHERE o.status = 'completed'), 0)::numeric,
    COALESCE(round(avg(o.total) FILTER (WHERE o.status = 'completed'), 0), 0)::numeric,
    CASE
      WHEN count(*) FILTER (WHERE o.ready_at IS NOT NULL) = 0 THEN NULL
      ELSE round(
        100.0
        * count(*) FILTER (WHERE o.ready_at IS NOT NULL AND o.ready_at <= o.expected_arrival_at)
        / count(*) FILTER (WHERE o.ready_at IS NOT NULL),
        0
      )
    END,
    (
      SELECT round(
        percentile_cont(0.5) WITHIN GROUP (
          ORDER BY extract(epoch FROM (o2.ready_at - o2.accepted_at)) / 60
        )::numeric,
        0
      )
      FROM o o2
      WHERE o2.ready_at IS NOT NULL AND o2.accepted_at IS NOT NULL
    ),
    r.rating,
    r.rating_count
  FROM o
  RIGHT JOIN public.restaurants r ON r.id = _restaurant_id
  GROUP BY r.rating, r.rating_count;
END;
$$;

REVOKE ALL ON FUNCTION public.vendor_summary(UUID, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.vendor_summary(UUID, INT) TO authenticated;

-- ---------------------------------------------------------------------------
-- Takings per day, for the trend line. Gaps are filled with zeroes so a quiet
-- day reads as a dip rather than vanishing and distorting the shape.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.vendor_daily(_restaurant_id UUID, _days INT DEFAULT 14)
RETURNS TABLE (day DATE, orders BIGINT, takings NUMERIC)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
#variable_conflict use_column
DECLARE
  span INT := LEAST(GREATEST(COALESCE(_days, 14), 1), 90);
BEGIN
  PERFORM public.assert_owns_restaurant(_restaurant_id);

  RETURN QUERY
  SELECT
    d::date,
    count(o.id)::bigint,
    COALESCE(sum(o.total) FILTER (WHERE o.status = 'completed'), 0)::numeric
  FROM generate_series(
         (now() AT TIME ZONE 'Africa/Dar_es_Salaam')::date - (span - 1),
         (now() AT TIME ZONE 'Africa/Dar_es_Salaam')::date,
         '1 day'
       ) d
  LEFT JOIN public.orders o
    ON o.restaurant_id = _restaurant_id
   AND (o.created_at AT TIME ZONE 'Africa/Dar_es_Salaam')::date = d::date
  GROUP BY d
  ORDER BY d;
END;
$$;

REVOKE ALL ON FUNCTION public.vendor_daily(UUID, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.vendor_daily(UUID, INT) TO authenticated;

-- ---------------------------------------------------------------------------
-- Best sellers. Reads the order_items snapshots, not the live menu, so a dish
-- that has since been renamed or deleted still shows what it actually sold.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.vendor_top_dishes(
  _restaurant_id UUID,
  _days INT DEFAULT 30,
  _limit INT DEFAULT 10
)
RETURNS TABLE (name TEXT, qty BIGINT, takings NUMERIC)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
#variable_conflict use_column
DECLARE
  since TIMESTAMPTZ := now() - make_interval(days => GREATEST(COALESCE(_days, 30), 1));
BEGIN
  PERFORM public.assert_owns_restaurant(_restaurant_id);

  RETURN QUERY
  SELECT oi.name, sum(oi.qty)::bigint, sum(oi.line_total)::numeric
  FROM public.order_items oi
  JOIN public.orders o ON o.id = oi.order_id
  WHERE o.restaurant_id = _restaurant_id
    AND o.created_at >= since
    AND o.status = 'completed'
  GROUP BY oi.name
  ORDER BY sum(oi.qty) DESC, oi.name ASC
  LIMIT LEAST(GREATEST(COALESCE(_limit, 10), 1), 50);
END;
$$;

REVOKE ALL ON FUNCTION public.vendor_top_dishes(UUID, INT, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.vendor_top_dishes(UUID, INT, INT) TO authenticated;

-- ---------------------------------------------------------------------------
-- Busiest hours, in local time — what a kitchen actually staffs against.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.vendor_busiest_hours(_restaurant_id UUID, _days INT DEFAULT 30)
RETURNS TABLE (hour INT, orders BIGINT)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
#variable_conflict use_column
DECLARE
  since TIMESTAMPTZ := now() - make_interval(days => GREATEST(COALESCE(_days, 30), 1));
BEGIN
  PERFORM public.assert_owns_restaurant(_restaurant_id);

  RETURN QUERY
  SELECT
    h::int,
    count(o.id)::bigint
  FROM generate_series(0, 23) h
  LEFT JOIN public.orders o
    ON o.restaurant_id = _restaurant_id
   AND o.created_at >= since
   AND extract(hour FROM (o.expected_arrival_at AT TIME ZONE 'Africa/Dar_es_Salaam')) = h
  GROUP BY h
  ORDER BY h;
END;
$$;

REVOKE ALL ON FUNCTION public.vendor_busiest_hours(UUID, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.vendor_busiest_hours(UUID, INT) TO authenticated;
