/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorBillingRouteImport } from './routes/vendor.billing'
import { Route as VendorInsightsRouteImport } from './routes/vendor.insights'
import { Route as VendorMenuRouteImport } from './routes/vendor.menu'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorSetupRouteImport } from './routes/vendor.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorBillingRoute = VendorBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInsightsRoute = VendorInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => VendorRoute,
} as any)
const VendorMenuRoute = VendorMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSetupRoute = VendorSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => VendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRoute
  '/vendor/billing': typeof VendorBillingRoute
  '/vendor/insights': typeof VendorInsightsRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/setup': typeof VendorSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRoute
  '/vendor/billing': typeof VendorBillingRoute
  '/vendor/insights': typeof VendorInsightsRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/setup': typeof VendorSetupRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRoute
  '/vendor/billing': typeof VendorBillingRoute
  '/vendor/insights': typeof VendorInsightsRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/setup': typeof VendorSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/bootstrap'
    | '/cart'
    | '/orders'
    | '/privacy'
    | '/search'
    | '/vendor'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/vendor/billing'
    | '/vendor/insights'
    | '/vendor/menu'
    | '/vendor/profile'
    | '/vendor/setup'
    | '/admin/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/bootstrap'
    | '/cart'
    | '/orders'
    | '/privacy'
    | '/search'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/vendor/billing'
    | '/vendor/insights'
    | '/vendor/menu'
    | '/vendor/profile'
    | '/vendor/setup'
    | '/admin'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/bootstrap'
    | '/cart'
    | '/orders'
    | '/privacy'
    | '/search'
    | '/vendor'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/vendor/billing'
    | '/vendor/insights'
    | '/vendor/menu'
    | '/vendor/profile'
    | '/vendor/setup'
    | '/admin/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  VendorRoute: typeof VendorRouteWithChildren
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/billing': {
      id: '/vendor/billing'
      path: '/billing'
      fullPath: '/vendor/billing'
      preLoaderRoute: typeof VendorBillingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/insights': {
      id: '/vendor/insights'
      path: '/insights'
      fullPath: '/vendor/insights'
      preLoaderRoute: typeof VendorInsightsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/menu': {
      id: '/vendor/menu'
      path: '/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof VendorMenuRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/setup': {
      id: '/vendor/setup'
      path: '/setup'
      fullPath: '/vendor/setup'
      preLoaderRoute: typeof VendorSetupRouteImport
      parentRoute: typeof VendorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendorRouteChildren {
  VendorBillingRoute: typeof VendorBillingRoute
  VendorInsightsRoute: typeof VendorInsightsRoute
  VendorMenuRoute: typeof VendorMenuRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorSetupRoute: typeof VendorSetupRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorBillingRoute: VendorBillingRoute,
  VendorInsightsRoute: VendorInsightsRoute,
  VendorMenuRoute: VendorMenuRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorSetupRoute: VendorSetupRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  VendorRoute: VendorRouteWithChildren,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
